<?php
        $User_Information = [
                                [
                                    "UserID"=>01,
                                    "Name"=>"Maham",
                                    "Age"=>25,
                                    "PhoneNumber"=>"090078601"
                                ],
                                [
                                    "UserID"=>02,
                                    "Name"=>"Aliza",
                                    "Age"=>19,
                                    "PhoneNumber"=>"090078602"
                                ],
                                [
                                    "UserID"=>03,
                                    "Name"=>"Hasan",
                                    "Age"=>32,
                                    "PhoneNumber"=>"090078603"
                                ],
                                [
                                    "UserID"=>04,
                                    "Name"=>"Zain",
                                    "Age"=>28,
                                    "PhoneNumber"=>"090078604"
                                ],
                                [
                                    "UserID"=>05,
                                    "Name"=>"Sumbul",
                                    "Age"=>65,
                                    "PhoneNumber"=>"090078605"
                                ]
                            ];
        $User_Credentials=[
                            [
                                "VisitingUser"=>01,
                                "Email"=>"thisisme@gmail.com",
                                "Password"=>"thisisme",
                                "UserInformationID"=>05
                            ],
                            [
                                "VisitingUser"=>02,
                                "Email"=>"thisismeagain@gmail.com",
                                "Password"=>"thisismeagain",
                                "UserInformationID"=>04
                            ],
                            [
                                "VisitingUser"=>03,
                                "Email"=>"testingid@gmail.com",
                                "Password"=>"testingid",
                                "UserInformationID"=>03     
                            ],
                            [
                                "VisitingUser"=>04,
                                "Email"=>"testingidone@gmail.com",
                                "Password"=>"testingidone",
                                "UserInformationID"=>02
                            ],
                            [
                                "VisitingUser"=>05,
                                "Email"=>"testingidtwo@gmail.com",
                                "Password"=>"testingidtwo",
                                "UserInformationID"=>01
                            ]
                        ];
?>